import { AwsClient } from "aws4fetch";

export type R2Config = {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
  endpoint: string;
};

const env = (...keys: string[]) => keys.map((key) => process.env[key]?.trim() ?? "").find(Boolean) ?? "";

export function getR2Config(): R2Config | null {
  const accountId = env("CLOUDFLARE_ACCOUNT_ID", "R2_ACCOUNT_ID");
  const accessKeyId = env("CLOUDFLARE_R2_ACCESS_KEY_ID", "R2_ACCESS_KEY_ID");
  const secretAccessKey = env("CLOUDFLARE_R2_SECRET_ACCESS_KEY", "R2_SECRET_ACCESS_KEY");
  const bucket = env("CLOUDFLARE_R2_BUCKET", "CLOUDFLARE_R2_BUCKET_NAME", "R2_BUCKET_NAME");
  const endpointOverride = env("CLOUDFLARE_R2_ENDPOINT", "R2_ENDPOINT");

  if (!accessKeyId || !secretAccessKey || !bucket || (!accountId && !endpointOverride)) return null;
  if (!/^[a-z0-9-]{3,63}$/i.test(bucket)) return null;
  if (!endpointOverride && !/^[a-f0-9]{32}$/i.test(accountId)) return null;

  const endpoint = (endpointOverride || `https://${accountId}.r2.cloudflarestorage.com`).replace(/\/+$/, "");
  if (!/^https:\/\//i.test(endpoint)) return null;

  return { accountId, accessKeyId, secretAccessKey, bucket, endpoint };
}

function createR2Client(config: R2Config) {
  return new AwsClient({
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    service: "s3",
    region: "auto",
    retries: 1,
  });
}

function objectUrl(config: R2Config, key: string) {
  // Keys are generated by the server and restricted to safe ASCII path segments.
  return `${config.endpoint}/${config.bucket}/${key}`;
}

/** Store a validated image in the configured private R2 bucket. */
export async function putR2Object(key: string, body: ArrayBuffer, contentType: string) {
  const config = getR2Config();
  if (!config) throw new Error("cloudflare_r2_not_configured");

  const response = await createR2Client(config).fetch(objectUrl(config, key), {
    method: "PUT",
    headers: {
      "Content-Type": contentType,
      "Cache-Control": "public, max-age=31536000, immutable",
    },
    body,
  });

  if (!response.ok) {
    console.error("[Cloudflare R2] Upload failed with status", response.status);
    throw new Error("cloudflare_r2_upload_failed");
  }
}

export async function deleteR2Object(key: string) {
  const config = getR2Config();
  if (!config) throw new Error("cloudflare_r2_not_configured");
  const response = await createR2Client(config).fetch(objectUrl(config, key), { method: "DELETE" });
  if (!response.ok && response.status !== 204) {
    console.error("[Cloudflare R2] Delete failed with status", response.status);
    throw new Error("cloudflare_r2_delete_failed");
  }
}

/** Returns the stored image, null only when the object is absent or R2 is not configured. */
export async function getR2Object(key: string): Promise<{ body: ArrayBuffer; contentType: string } | null> {
  const config = getR2Config();
  if (!config) return null;

  const response = await createR2Client(config).fetch(objectUrl(config, key), { method: "GET" });
  if (response.status === 404) return null;
  if (!response.ok) {
    console.error("[Cloudflare R2] Read failed with status", response.status);
    throw new Error("cloudflare_r2_read_failed");
  }

  return {
    body: await response.arrayBuffer(),
    contentType: response.headers.get("content-type") ?? "application/octet-stream",
  };
}

/** Performs a real, temporary write/delete against the configured bucket. Never returns credentials. */
export async function probeR2Connection(): Promise<{ configured: boolean; connected: boolean; status: number | null }> {
  const config = getR2Config();
  if (!config) return { configured: false, connected: false, status: null };

  const key = `_diagnostics/${crypto.randomUUID()}.txt`;
  const client = createR2Client(config);
  try {
    const put = await client.fetch(objectUrl(config, key), {
      method: "PUT",
      headers: { "Content-Type": "text/plain", "Cache-Control": "no-store" },
      body: "eternal-r2-connection-test",
    });
    if (!put.ok) {
      console.error("[Cloudflare R2] Connection probe write failed with status", put.status);
      return { configured: true, connected: false, status: put.status };
    }

    const del = await client.fetch(objectUrl(config, key), { method: "DELETE" });
    const connected = del.ok || del.status === 204;
    if (!connected) console.error("[Cloudflare R2] Connection probe cleanup failed with status", del.status);
    return { configured: true, connected, status: del.status };
  } catch {
    return { configured: true, connected: false, status: null };
  }
}
