-- Coleção de 10 molduras animadas Eternal. Idempotente por slug; não toca em saldos ou inventários.
INSERT INTO public.cosmetics
(slug,name,description,kind,rarity,preview,animation,required_level,required_plan,active,coin_price,availability,event_slug,sort,in_shop,sold,effect,media_type,frame_category,featured,released_at,after_event,exclusive_tag,keep_after_plan)
VALUES
('celestial-dragon-frame','Celestial Dragon','Escamas celestiais, cristais azul-violeta e energia que percorre as órbitas.','frame','legendary','#60a5fa','drift',1,'free',true,780,'shop',NULL,201,true,0,'{"style":"galaxy","intensity":1.2,"speed":1.1,"size":1.1}'::jsonb,'image','fantasia',true,now(),'keep',NULL,false),
('eternal-phoenix-frame','Eternal Phoenix','Chamas rubras e douradas, penas de luz ascendentes e renascimento em ondas.','frame','mythic','#f97316','pulse',1,'free',true,1200,'shop',NULL,202,true,0,'{"style":"fire","intensity":1.35,"speed":1.2,"size":1.15}'::jsonb,'image','elemental',true,now(),'keep',NULL,false),
('galaxy-sovereign-frame','Galaxy Sovereign','Nebulosa violeta, anéis cósmicos em ritmos diferentes e estrelas orbitais.','frame','mythic','#c084fc','drift',1,'free',true,1150,'shop',NULL,203,true,0,'{"style":"galaxy","intensity":1.3,"speed":1.25,"size":1.15}'::jsonb,'image','fantasia',true,now(),'keep',NULL,false),
('kitsune-spirit-frame','Kitsune Spirit','Orelhas de raposa, selos arcanos e pequenas chamas espirituais.','frame','epic','#fb7185','spin',1,'free',true,620,'shop',NULL,204,true,0,'{"style":"magic","intensity":1.1,"speed":1.1,"size":1.1}'::jsonb,'image','anime',true,now(),'keep',NULL,false),
('moonlit-garden-frame','Moonlit Garden','Flores noturnas, lua perolada, pétalas flutuantes e borboletas luminosas.','frame','epic','#c4b5fd','drift',1,'free',true,590,'shop',NULL,205,true,0,'{"style":"aura","intensity":1,"speed":1,"size":1.05}'::jsonb,'image','especial',true,now(),'keep',NULL,false),
('bunny-dreamland-frame','Bunny Dreamland','Coelhinho pastel caminhando entre nuvens, corações e estrelinhas.','frame','epic','#f9a8d4','drift',1,'free',true,560,'shop',NULL,206,true,0,'{"style":"aura","intensity":1,"speed":1.15,"size":1.1}'::jsonb,'image','cute',true,now(),'keep',NULL,false),
('midnight-cat-frame','Midnight Cat','Gato noturno com lua crescente, olhos cintilantes e pegadas mágicas.','frame','rare','#818cf8','spin',1,'free',true,390,'shop',NULL,207,true,0,'{"style":"dark","intensity":0.95,"speed":1.1,"size":1.05}'::jsonb,'image','cute',true,now(),'keep',NULL,false),
('halloween-phantom-frame','Halloween Phantom','Fantasmas travessos, abóboras acesas, névoa violeta e morcegos.','frame','epic','#a855f7','pulse',1,'free',true,640,'shop','halloween',208,true,0,'{"style":"dark","intensity":1.15,"speed":1.1,"size":1.1}'::jsonb,'image','eventos',true,now(),'archive','event',false),
('christmas-wonderland-frame','Christmas Wonderland','Galhos festivos, luzes cintilantes, neve e ornamentos dourados.','frame','epic','#22c55e','drift',1,'free',true,640,'shop','christmas',209,true,0,'{"style":"ice","intensity":1.05,"speed":1,"size":1.1}'::jsonb,'image','eventos',true,now(),'archive','event',false),
('sakura-spring-frame','Sakura Spring','Flores de cerejeira, pétalas em curva e borboletas cor-de-rosa.','frame','epic','#f472b6','drift',1,'free',true,600,'shop','sakura-spring',210,true,0,'{"style":"aura","intensity":1.05,"speed":1.1,"size":1.05}'::jsonb,'image','eventos',true,now(),'archive','event',false)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,rarity=EXCLUDED.rarity,preview=EXCLUDED.preview,animation=EXCLUDED.animation,coin_price=EXCLUDED.coin_price,active=true,in_shop=true,effect=EXCLUDED.effect,frame_category=EXCLUDED.frame_category,event_slug=EXCLUDED.event_slug,featured=true;
