/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApoiarRouteImport } from './routes/_authenticated/apoiar'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAtividadeRouteImport } from './routes/_authenticated/atividade'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedHallDaFamaRouteImport } from './routes/_authenticated/hall-da-fama'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedPersonalizarRouteImport } from './routes/_authenticated/personalizar'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated/scans'
import { Route as AuthenticatedSejaParceiroRouteImport } from './routes/_authenticated/seja-parceiro'
import { Route as AuthenticatedObraSlugRouteImport } from './routes/_authenticated/obra.$slug'
import { Route as AuthenticatedPerfilUsernameRouteImport } from './routes/_authenticated/perfil.$username'
import { Route as AuthenticatedScanSlugRouteImport } from './routes/_authenticated/scan.$slug'
import { Route as AuthenticatedAdminObrasIdRouteImport } from './routes/_authenticated/admin_.obras.$id'
import { Route as AuthenticatedLerObraCapituloRouteImport } from './routes/_authenticated/ler.$obra.$capitulo'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApoiarRoute = AuthenticatedApoiarRouteImport.update({
  id: '/apoiar',
  path: '/apoiar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadeRoute = AuthenticatedAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHallDaFamaRoute = AuthenticatedHallDaFamaRouteImport.update({
  id: '/hall-da-fama',
  path: '/hall-da-fama',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalizarRoute =
  AuthenticatedPersonalizarRouteImport.update({
    id: '/personalizar',
    path: '/personalizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSejaParceiroRoute =
  AuthenticatedSejaParceiroRouteImport.update({
    id: '/seja-parceiro',
    path: '/seja-parceiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObraSlugRoute = AuthenticatedObraSlugRouteImport.update({
  id: '/obra/$slug',
  path: '/obra/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilUsernameRoute =
  AuthenticatedPerfilUsernameRouteImport.update({
    id: '/perfil/$username',
    path: '/perfil/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanSlugRoute = AuthenticatedScanSlugRouteImport.update({
  id: '/scan/$slug',
  path: '/scan/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminObrasIdRoute =
  AuthenticatedAdminObrasIdRouteImport.update({
    id: '/admin_/obras/$id',
    path: '/admin/obras/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLerObraCapituloRoute =
  AuthenticatedLerObraCapituloRouteImport.update({
    id: '/ler/$obra/$capitulo',
    path: '/ler/$obra/$capitulo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/convite': typeof ConviteRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apoiar': typeof AuthenticatedApoiarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/hall-da-fama': typeof AuthenticatedHallDaFamaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/me': typeof AuthenticatedMeRoute
  '/personalizar': typeof AuthenticatedPersonalizarRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/scans': typeof AuthenticatedScansRoute
  '/seja-parceiro': typeof AuthenticatedSejaParceiroRoute
  '/obra/$slug': typeof AuthenticatedObraSlugRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/scan/$slug': typeof AuthenticatedScanSlugRoute
  '/admin/obras/$id': typeof AuthenticatedAdminObrasIdRoute
  '/ler/$obra/$capitulo': typeof AuthenticatedLerObraCapituloRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/convite': typeof ConviteRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apoiar': typeof AuthenticatedApoiarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/hall-da-fama': typeof AuthenticatedHallDaFamaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/me': typeof AuthenticatedMeRoute
  '/personalizar': typeof AuthenticatedPersonalizarRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/scans': typeof AuthenticatedScansRoute
  '/seja-parceiro': typeof AuthenticatedSejaParceiroRoute
  '/obra/$slug': typeof AuthenticatedObraSlugRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/scan/$slug': typeof AuthenticatedScanSlugRoute
  '/admin/obras/$id': typeof AuthenticatedAdminObrasIdRoute
  '/ler/$obra/$capitulo': typeof AuthenticatedLerObraCapituloRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/convite': typeof ConviteRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apoiar': typeof AuthenticatedApoiarRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/atividade': typeof AuthenticatedAtividadeRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/hall-da-fama': typeof AuthenticatedHallDaFamaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/personalizar': typeof AuthenticatedPersonalizarRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/seja-parceiro': typeof AuthenticatedSejaParceiroRoute
  '/_authenticated/obra/$slug': typeof AuthenticatedObraSlugRoute
  '/_authenticated/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/_authenticated/scan/$slug': typeof AuthenticatedScanSlugRoute
  '/_authenticated/admin_/obras/$id': typeof AuthenticatedAdminObrasIdRoute
  '/_authenticated/ler/$obra/$capitulo': typeof AuthenticatedLerObraCapituloRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/convite'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/admin'
    | '/apoiar'
    | '/assinatura'
    | '/atividade'
    | '/atualizacoes'
    | '/configuracoes'
    | '/conquistas'
    | '/explorar'
    | '/favoritos'
    | '/hall-da-fama'
    | '/historico'
    | '/inicio'
    | '/loja'
    | '/me'
    | '/personalizar'
    | '/planos'
    | '/ranking'
    | '/scans'
    | '/seja-parceiro'
    | '/obra/$slug'
    | '/perfil/$username'
    | '/scan/$slug'
    | '/admin/obras/$id'
    | '/ler/$obra/$capitulo'
    | '/api/public/media/$'
    | '/api/public/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/convite'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/admin'
    | '/apoiar'
    | '/assinatura'
    | '/atividade'
    | '/atualizacoes'
    | '/configuracoes'
    | '/conquistas'
    | '/explorar'
    | '/favoritos'
    | '/hall-da-fama'
    | '/historico'
    | '/inicio'
    | '/loja'
    | '/me'
    | '/personalizar'
    | '/planos'
    | '/ranking'
    | '/scans'
    | '/seja-parceiro'
    | '/obra/$slug'
    | '/perfil/$username'
    | '/scan/$slug'
    | '/admin/obras/$id'
    | '/ler/$obra/$capitulo'
    | '/api/public/media/$'
    | '/api/public/webhooks/asaas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/convite'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/apoiar'
    | '/_authenticated/assinatura'
    | '/_authenticated/atividade'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conquistas'
    | '/_authenticated/explorar'
    | '/_authenticated/favoritos'
    | '/_authenticated/hall-da-fama'
    | '/_authenticated/historico'
    | '/_authenticated/inicio'
    | '/_authenticated/loja'
    | '/_authenticated/me'
    | '/_authenticated/personalizar'
    | '/_authenticated/planos'
    | '/_authenticated/ranking'
    | '/_authenticated/scans'
    | '/_authenticated/seja-parceiro'
    | '/_authenticated/obra/$slug'
    | '/_authenticated/perfil/$username'
    | '/_authenticated/scan/$slug'
    | '/_authenticated/admin_/obras/$id'
    | '/_authenticated/ler/$obra/$capitulo'
    | '/api/public/media/$'
    | '/api/public/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConviteRoute: typeof ConviteRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apoiar': {
      id: '/_authenticated/apoiar'
      path: '/apoiar'
      fullPath: '/apoiar'
      preLoaderRoute: typeof AuthenticatedApoiarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividade': {
      id: '/_authenticated/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthenticatedAtividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hall-da-fama': {
      id: '/_authenticated/hall-da-fama'
      path: '/hall-da-fama'
      fullPath: '/hall-da-fama'
      preLoaderRoute: typeof AuthenticatedHallDaFamaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personalizar': {
      id: '/_authenticated/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof AuthenticatedPersonalizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seja-parceiro': {
      id: '/_authenticated/seja-parceiro'
      path: '/seja-parceiro'
      fullPath: '/seja-parceiro'
      preLoaderRoute: typeof AuthenticatedSejaParceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obra/$slug': {
      id: '/_authenticated/obra/$slug'
      path: '/obra/$slug'
      fullPath: '/obra/$slug'
      preLoaderRoute: typeof AuthenticatedObraSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/$username': {
      id: '/_authenticated/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof AuthenticatedPerfilUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/$slug': {
      id: '/_authenticated/scan/$slug'
      path: '/scan/$slug'
      fullPath: '/scan/$slug'
      preLoaderRoute: typeof AuthenticatedScanSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/obras/$id': {
      id: '/_authenticated/admin_/obras/$id'
      path: '/admin/obras/$id'
      fullPath: '/admin/obras/$id'
      preLoaderRoute: typeof AuthenticatedAdminObrasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ler/$obra/$capitulo': {
      id: '/_authenticated/ler/$obra/$capitulo'
      path: '/ler/$obra/$capitulo'
      fullPath: '/ler/$obra/$capitulo'
      preLoaderRoute: typeof AuthenticatedLerObraCapituloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApoiarRoute: typeof AuthenticatedApoiarRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAtividadeRoute: typeof AuthenticatedAtividadeRoute
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedHallDaFamaRoute: typeof AuthenticatedHallDaFamaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPersonalizarRoute: typeof AuthenticatedPersonalizarRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedSejaParceiroRoute: typeof AuthenticatedSejaParceiroRoute
  AuthenticatedObraSlugRoute: typeof AuthenticatedObraSlugRoute
  AuthenticatedPerfilUsernameRoute: typeof AuthenticatedPerfilUsernameRoute
  AuthenticatedScanSlugRoute: typeof AuthenticatedScanSlugRoute
  AuthenticatedAdminObrasIdRoute: typeof AuthenticatedAdminObrasIdRoute
  AuthenticatedLerObraCapituloRoute: typeof AuthenticatedLerObraCapituloRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApoiarRoute: AuthenticatedApoiarRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAtividadeRoute: AuthenticatedAtividadeRoute,
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedHallDaFamaRoute: AuthenticatedHallDaFamaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPersonalizarRoute: AuthenticatedPersonalizarRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedSejaParceiroRoute: AuthenticatedSejaParceiroRoute,
  AuthenticatedObraSlugRoute: AuthenticatedObraSlugRoute,
  AuthenticatedPerfilUsernameRoute: AuthenticatedPerfilUsernameRoute,
  AuthenticatedScanSlugRoute: AuthenticatedScanSlugRoute,
  AuthenticatedAdminObrasIdRoute: AuthenticatedAdminObrasIdRoute,
  AuthenticatedLerObraCapituloRoute: AuthenticatedLerObraCapituloRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConviteRoute: ConviteRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
